package com.sidequestlab.floatingvoice.core;

public enum OverlayEvent {
    TAP,
    LONG_PRESS,
    GESTURE_CANCELED,
    VOICE_START_SUCCEEDED,
    VOICE_START_FAILED,
    CANCEL_VOICE_REQUESTED,
    VOICE_CANCEL_SUCCEEDED,
    VOICE_CANCEL_FAILED,
    VOICE_STOP_SUCCEEDED,
    VOICE_STOP_FAILED,
    VOICE_QUEUED,
    VOICE_REJECTED,
    COMPOSE_TEXT,
    SUBMIT_TEXT,
    TEXT_QUEUED,
    TEXT_REJECTED,
    TEXT_DELIVERED,
    TEARDOWN
}
